name: Waka Readme

on:
  push:
  schedule: # Run workflow automatically
    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch:
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-stats:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: matchai/waka-box@v4.0.5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}